@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


@echo off 

if not "%~1" == "" goto debugFile 

@echo on 

"D:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\common\bin\cspybat" -f "G:\Develop Guide\Blazar β Board\蓝宙电子_XTB009_锋速系列-KL26系统板资料-【更新至2015.11.16】\1参考例程\蓝宙电子KL2x开发板标准例程\LANDZO KL2X 实验25  光电码盘测速实验\landzo K2x\settings\landzo k2x.KL25_Release.general.xcl" --backend -f "G:\Develop Guide\Blazar β Board\蓝宙电子_XTB009_锋速系列-KL26系统板资料-【更新至2015.11.16】\1参考例程\蓝宙电子KL2x开发板标准例程\LANDZO KL2X 实验25  光电码盘测速实验\landzo K2x\settings\landzo k2x.KL25_Release.driver.xcl" 

@echo off 
goto end 

:debugFile 

@echo on 

"D:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\common\bin\cspybat" -f "G:\Develop Guide\Blazar β Board\蓝宙电子_XTB009_锋速系列-KL26系统板资料-【更新至2015.11.16】\1参考例程\蓝宙电子KL2x开发板标准例程\LANDZO KL2X 实验25  光电码盘测速实验\landzo K2x\settings\landzo k2x.KL25_Release.general.xcl" "--debug_file=%~1" --backend -f "G:\Develop Guide\Blazar β Board\蓝宙电子_XTB009_锋速系列-KL26系统板资料-【更新至2015.11.16】\1参考例程\蓝宙电子KL2x开发板标准例程\LANDZO KL2X 实验25  光电码盘测速实验\landzo K2x\settings\landzo k2x.KL25_Release.driver.xcl" 

@echo off 
:end