param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "D:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\common\bin\cspybat" -f "G:\Develop Guide\Blazar β Board\蓝宙电子_XTB009_锋速系列-KL26系统板资料-【更新至2015.11.16】\1参考例程\蓝宙电子KL2x开发板标准例程\LANDZO KL2X 实验25  光电码盘测速实验\landzo K2x\settings\landzo k2x.KL25_Release.general.xcl" --backend -f "G:\Develop Guide\Blazar β Board\蓝宙电子_XTB009_锋速系列-KL26系统板资料-【更新至2015.11.16】\1参考例程\蓝宙电子KL2x开发板标准例程\LANDZO KL2X 实验25  光电码盘测速实验\landzo K2x\settings\landzo k2x.KL25_Release.driver.xcl" 
}
else
{
& "D:\Program Files (x86)\IAR Systems\Embedded Workbench 8.0\common\bin\cspybat" -f "G:\Develop Guide\Blazar β Board\蓝宙电子_XTB009_锋速系列-KL26系统板资料-【更新至2015.11.16】\1参考例程\蓝宙电子KL2x开发板标准例程\LANDZO KL2X 实验25  光电码盘测速实验\landzo K2x\settings\landzo k2x.KL25_Release.general.xcl" --debug_file=$debugfile --backend -f "G:\Develop Guide\Blazar β Board\蓝宙电子_XTB009_锋速系列-KL26系统板资料-【更新至2015.11.16】\1参考例程\蓝宙电子KL2x开发板标准例程\LANDZO KL2X 实验25  光电码盘测速实验\landzo K2x\settings\landzo k2x.KL25_Release.driver.xcl" 
}
